name:                sci-note
version:             0.1.0.0
github:              "TerenceNg03/sci-note"
license:             BSD-3-Clause
author:              "Terence Ng"
maintainer:          "example@example.com"
copyright:           "2023 Terence Ng"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TerenceNg03/sci-note#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- http-types
- network
- wai
- filepath
- stm
- containers
- aeson
- directory
- text
- log-base
- mtl
- optics
- fmt
- persistent-sqlite
- persistent
- esqueleto
- bytestring
- cmdargs


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  sci-note-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sci-note

tests:
  sci-note-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sci-note
